package InPatientManagementSystem;




import MYSQL.DBConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class ClinicDetails extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    public ClinicDetails() {
        initComponents();
        conn = DBConnect.connect();
        tableload1();
    }
    
    public ClinicDetails(String para){
        initComponents();
        IDField.setText(para);
        
    }
    
    private void tableload1() {
       try{
        String sql="SELECT PID,AdmittedDate,DischargeDate,DrName,Symptoms,Diagnosis,Prescriptions  FROM clinicreport";
         pst=conn.prepareStatement(sql); 
         rs=pst.executeQuery();
         
         clinictable.setModel(DbUtils.resultSetToTableModel(rs));
       }
        catch(Exception e){
     }
     }
    
    
    private void Reset1()
    {
        IDField.setText("");
        AdmittedDateField.setText("");
        DischargeDateField.setText("");
        DoctorBox.setSelectedIndex(0);
        SymptomsField.setText("");
        DiagnosisField.setText("");
        PrescriptionField.setText("");
        addReport.setEnabled(true);
        updateReport.setEnabled(true);
        DeleteReportButton.setEnabled(true);
        Report.setEnabled(true);
        printReport.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        DischargeDateField = new javax.swing.JTextField();
        AdmittedDateField = new javax.swing.JTextField();
        DoctorBox = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        SymptomsField = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        DiagnosisField = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        PrescriptionField = new javax.swing.JTextArea();
        IDField = new javax.swing.JTextField();
        addReport = new javax.swing.JButton();
        updateReport = new javax.swing.JButton();
        DeleteReportButton = new javax.swing.JButton();
        Report = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        clinictable = new javax.swing.JTable();
        printReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setText("Clinic Report");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(492, 492, 492)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel22)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel26.setText("Patient ID");

        jLabel125.setText("Admitted Date");

        jLabel126.setText("Doctor Name");

        jLabel127.setText("Symptoms");

        jLabel128.setText("Diagnosis");

        jLabel129.setText("Discharge Date");

        jLabel130.setText("Prescriptions");

        DoctorBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr. J.Karthikeyan", "Dr. S.Kajenthirakumar", "Dr. V.M.Emalton", "Dr. P.Kasvithan", "Dr. Hilton", "Dr. Shobana" }));

        SymptomsField.setColumns(20);
        SymptomsField.setRows(5);
        jScrollPane3.setViewportView(SymptomsField);

        DiagnosisField.setColumns(20);
        DiagnosisField.setRows(5);
        jScrollPane5.setViewportView(DiagnosisField);

        PrescriptionField.setColumns(20);
        PrescriptionField.setRows(5);
        jScrollPane6.setViewportView(PrescriptionField);

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel125)
                    .addComponent(jLabel129)
                    .addComponent(jLabel126)
                    .addComponent(jLabel127))
                .addGap(96, 96, 96)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DischargeDateField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(AdmittedDateField)
                            .addComponent(DoctorBox, 0, 1, Short.MAX_VALUE))
                        .addGap(148, 148, 148)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(jLabel130)
                                .addGap(59, 59, 59)
                                .addComponent(jScrollPane6))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(jLabel128)
                                .addGap(75, 75, 75)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel125)
                            .addComponent(AdmittedDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel129)
                            .addComponent(DischargeDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel128)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel130)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel126)
                            .addComponent(DoctorBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)))
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel127))
                .addGap(31, 31, 31))
        );

        addReport.setText("Add Report");
        addReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReportActionPerformed(evt);
            }
        });

        updateReport.setText("Update Report");
        updateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateReportActionPerformed(evt);
            }
        });

        DeleteReportButton.setText("Delete Report");
        DeleteReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteReportButtonActionPerformed(evt);
            }
        });

        Report.setText("Report");
        Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane7.setViewportView(jTextArea1);

        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Table", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        clinictable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        clinictable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clinictableMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(clinictable);

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        printReport.setText("Print Report");
        printReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(addReport, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(updateReport)
                .addGap(39, 39, 39)
                .addComponent(DeleteReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Report, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(printReport, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel21Layout.createSequentialGroup()
                                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane7))))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7))
                .addGap(18, 18, 18)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addReport, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Report, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printReport, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReportActionPerformed

        String PID=IDField.getText();
        String AddmittedDate=AdmittedDateField.getText();
        String DischargeDate=DischargeDateField.getText();
        String Doctor=DoctorBox.getSelectedItem().toString();
        String Symptoms=SymptomsField.getText();
        String Diagnosis=DiagnosisField.getText();
        String Prescription=PrescriptionField.getText();

        try{

            String q= "insert into clinicreport(PID,AdmittedDate,DischargeDate,DrName,Symptoms,Diagnosis,Prescriptions)values ('"+PID+"','"+AddmittedDate +"','"+DischargeDate +"','"+Doctor +"','"+Symptoms +"','"+Diagnosis +"','"+Prescription +"')";

            pst=conn.prepareStatement(q);

            pst.execute();
            //load table
            tableload1();
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_addReportActionPerformed

    private void updateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateReportActionPerformed

        int x= JOptionPane.showConfirmDialog(null,"Do you really want to update");
        if(x==0){
            String PID=IDField.getText();
            String AddmittedDate=AdmittedDateField.getText();
            String DischargeDate=DischargeDateField.getText();
            String Doctor=DoctorBox.getSelectedItem().toString();
            String Symptoms=SymptomsField.getText();
            String Diagnosis=DiagnosisField.getText();
            String Prescription=PrescriptionField.getText();

            String q="UPDATE clinicreport SET AddmittedDate='"+AddmittedDate+"',DischargeDate='"+DischargeDate+"',DrName='"+Doctor+"',Symptoms='"+Symptoms+"',Diagnosis='"+Diagnosis+"',Prescription='"+Prescription+"' where PID='"+PID+"'" ;
            try{
                pst=conn.prepareStatement(q);

                pst.execute();
                //load table
                tableload1();
            }
            catch(Exception e){

            }

        }
    }//GEN-LAST:event_updateReportActionPerformed

    private void DeleteReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteReportButtonActionPerformed
        int x=JOptionPane.showConfirmDialog(null, "Do you want to delete this");

        if(x==0){
            String PID=IDField.getText();

            String q="DELETE from clinicreport where PID='"+PID+"'";
            try{
                pst=conn.prepareStatement(q);
                pst.execute();

            }
            catch(Exception e){

            }
        }
    }//GEN-LAST:event_DeleteReportButtonActionPerformed

    private void ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportActionPerformed
        jTextArea1.setText("********************************************************************\n");
        jTextArea1.setText(jTextArea1.getText()+"                                    Patient Report                   \n");
        jTextArea1.setText(jTextArea1.getText()+"********************************************************************\n");

        Date obj = new Date();

        String date1 = obj.toString();

        jTextArea1.setText(jTextArea1.getText()+"\n\n"+date1+"\n\n\n");
        jTextArea1.setText(jTextArea1.getText()+"Patient ID : "+IDField.getText()+"\n\n");
        jTextArea1.setText(jTextArea1.getText()+"Admitted Date : "+AdmittedDateField.getText()+"\n\n");
        jTextArea1.setText(jTextArea1.getText()+"Discharge Date : "+DischargeDateField.getText()+"\n\n");
        jTextArea1.setText(jTextArea1.getText()+"Doctor : "+DoctorBox.getSelectedItem()+"\n\n");
        jTextArea1.setText(jTextArea1.getText()+"Symptoms : "+SymptomsField.getText()+"\n\n");
        jTextArea1.setText(jTextArea1.getText()+"Diagnosis : "+DiagnosisField.getText()+"\n\n");
        jTextArea1.setText(jTextArea1.getText()+"Prescription : "+PrescriptionField.getText()+"\n\n");

        jTextArea1.setText(jTextArea1.getText()+"        Delmon Hospital                                                                                       \n");
        jTextArea1.setText(jTextArea1.getText()+"        Colombo 06.                                                                                            \n");
    }//GEN-LAST:event_ReportActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed

        Reset1();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void clinictableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clinictableMouseClicked
        int r=clinictable.getSelectedRow();
        String PID=clinictable.getValueAt(r, 0).toString();
        String AdmittedDate=clinictable.getValueAt(r, 1).toString();
        String DischargeDate=clinictable.getValueAt(r, 2).toString();
        String DrName=clinictable.getValueAt(r, 3).toString();
        String Symptoms=clinictable.getValueAt(r, 4).toString();
        String Diagnosis=clinictable.getValueAt(r, 5).toString();
        String Prescriptions=clinictable.getValueAt(r, 6).toString();

        AdmittedDateField.setText(AdmittedDate);
        DischargeDateField.setText(DischargeDate);
        DoctorBox.setSelectedItem(DrName);
        SymptomsField.setText(Symptoms);
        DiagnosisField.setText(Diagnosis);
        PrescriptionField.setText(Prescriptions);

        IDField.setText(PID);
    }//GEN-LAST:event_clinictableMouseClicked

    private void printReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printReportActionPerformed
        try{
            jTextArea1.print();
        }catch(Exception e)
        {

        }
    }//GEN-LAST:event_printReportActionPerformed

    public void ClinicDetails(String msg){
        Connection conn = DBConnect.connect();
        String PID=IDField.getText();
        String q="select * from wardpayment where PID= IDField1 ";
           
         try {
             pst=conn.prepareStatement(q);
             pst.setString(1,msg);
             rs=pst.executeQuery();
              if(rs.next()){
                  String msg1=rs.getString("AdmittedDate");
                   AdmittedDateField.setText(msg1);
                   
                   String msg2=rs.getString("DischargeDate");
                   DischargeDateField.setText(msg2);
                   
                   
              
              }
             conn.close();
             
         } catch (SQLException ex) {
             Logger.getLogger(ClinicDetails.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClinicDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClinicDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClinicDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClinicDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClinicDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdmittedDateField;
    private javax.swing.JButton DeleteReportButton;
    private javax.swing.JTextArea DiagnosisField;
    private javax.swing.JTextField DischargeDateField;
    private javax.swing.JComboBox<String> DoctorBox;
    private javax.swing.JTextField IDField;
    private javax.swing.JTextArea PrescriptionField;
    private javax.swing.JButton Report;
    private javax.swing.JTextArea SymptomsField;
    private javax.swing.JButton addReport;
    private javax.swing.JButton clearButton;
    private javax.swing.JTable clinictable;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton printReport;
    private javax.swing.JButton updateReport;
    // End of variables declaration//GEN-END:variables
}
