package HumanResourceManagement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author hilton
 */
public class Attendance extends javax.swing.JFrame {

    /**
     * Creates new form Attendance
     */
    Connection con;
    boolean morning=false;
    boolean evening=false;
    
    int dates;
    String id;
    
    public Attendance() {
        initComponents();
        la_text.setText("");
        DateFormat time = new SimpleDateFormat("HH:mm:ss");
        
	Date timeformat = new Date();
	la_time.setText(time.format(timeformat));
        
        DateFormat date = new SimpleDateFormat("yyyy/MM/dd");
        Date dateformat=new Date();
        la_Date.setText(date.format(dateformat));
    
        DateFormat date1 = new SimpleDateFormat("dd");
        Date dateformat1=new Date();
        dates=Integer.parseInt(date1.format(dateformat));
        try
        {
            con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
            //JOptionPane.showMessageDialog(null,"connected with "+con.toString());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"not connect to server and message is"+e.getMessage());
        }
        
        int timesystem=Integer.parseInt(la_time.getText().substring(0,2));
        if(timesystem>=1 && timesystem<=12)
        {
            morning=true;
            evening=false;
            
            txt_username.setEnabled(true);
            txt_password.setEnabled(true);
            bt_login.setEnabled(true);
            bt_cancel.setEnabled(true);
        }
        else if(timesystem>=13 && timesystem<=23)
        {
            morning=false;
            evening=true;
            
            txt_username.setEnabled(true);
            txt_password.setEnabled(true);
            
            bt_login.setEnabled(true);
            bt_cancel.setEnabled(true);
        }
        else
        {
            txt_username.setEnabled(false);
            txt_password.setEnabled(false);
            
            bt_login.setEnabled(false);
            bt_cancel.setEnabled(false);
            
            la_text.setText("Not allowed to login");
        }
        
        String sql = "SELECT * FROM daily_attendance";
 

        try
        {
            
            Statement statement = con.createStatement();
            ResultSet result = statement.executeQuery(sql);
 
            int rows=0;
            while(result.next())
            {
                rows++;
                String idd = result.getString(1);
                id="DA"+(Integer.parseInt(idd.substring(2,9))+1);
            }
            if(rows<1)
            {
                id="DA1111111";
            }
        }
        catch(SQLException ex)
        {
            id="DA1111111";
        }
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bt_login = new javax.swing.JButton();
        bt_cancel = new javax.swing.JButton();
        la_time = new javax.swing.JLabel();
        la_text = new javax.swing.JLabel();
        la_Date = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        jLabel4.setText("Password");

        bt_login.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        bt_login.setText("Login");
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });

        bt_cancel.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        bt_cancel.setText("Cancel");
        bt_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelActionPerformed(evt);
            }
        });

        la_time.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        la_time.setText("Time");

        la_text.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N

        la_Date.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        la_Date.setText("Date");

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(la_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(266, 266, 266)
                        .addComponent(la_time, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(110, 110, 110)
                                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(119, 119, 119)
                                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                        .addComponent(la_text, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(149, 149, 149))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addComponent(bt_cancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_Date)
                            .addComponent(la_time))))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(la_text)))
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(304, 304, 304))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        // TODO add your handling code here:
        if(txt_username.getText().equals("") || txt_password.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Input Usename and Password");
        }
        else
        {
            boolean login=false;
            String sql1 = "SELECT * FROM login_employee";
            try
            {
                Statement statement1 = con.createStatement();
                ResultSet result = statement1.executeQuery(sql1);

                int count = 0;

                while (result.next())
                {
                    if(txt_username.getText().equals(result.getString(2)) && txt_password.getText().equals(result.getString(3)))
                    {
                        login=true;
                        break;
                    }
                    else
                    {
                        login=false;
                    }
                }
                
                if(login)
                {
                    int rows1=0;
                    String sql3 = "SELECT * FROM `daily_attendance` WHERE `Employeeid`='"+txt_username.getText()+"'";

                    try
                    {
                        Statement statement3 = con.createStatement();
                        ResultSet result3 = statement3.executeQuery(sql3);


                        
                        while(result3.next())
                        {
                            rows1++;
                        }
                        }
                    catch(SQLException ex)
                    {
                    }
                    
                    int rowsInserted=0;
                    if(morning ==true && evening ==false )
                    {
                        if(rows1<1)
                        {
                            la_text.setText("Login Successfuly");
                            try
                            {
                                double day=0;
                                if(Integer.parseInt(la_time.getText().substring(0,2))>9)
                                {
                                
                                    day=0.5;
                                }
                                else
                                {
                                    day=1;
                                }
                                String sql = "INSERT INTO `daily_attendance` (`id`,`EnteredTime`,`LeavedTime`,`Day`,`Employeeid`) VALUES (?, ?, ?, ?, ?)";
                                PreparedStatement statement = con.prepareStatement(sql);
                                statement.setString(1,id);
                                statement.setString(2,la_time.getText().toString());
                                statement.setString(3,"");
                                statement.setDouble(4,day);
                                statement.setString(5,txt_username.getText());

                
                                rowsInserted = statement.executeUpdate();
                
                        
                            }
                            catch(SQLException ex)
                            {
                                JOptionPane.showMessageDialog(null, ex.getMessage());
                            }
                            if (rowsInserted > 0)
                            {
                                JOptionPane.showMessageDialog(null,"Login successfully! Welcome ");

                                String sql2 = "SELECT * FROM daily_attendance";

                            try
                            {

                                Statement statement2 = con.createStatement();
                                ResultSet result1 = statement2.executeQuery(sql2);


                                int rows=0;
                                while(result1.next())
                                {
                                    rows++;
                                    String idd = result1.getString(1);
                                    id="DA"+(Integer.parseInt(idd.substring(2,9))+1);
                                }
                                if(rows<1)
                                {
                                    id="DA1111111";
                                }
                            }
                            catch(SQLException ex)
                            {
                                id="DA1111111";
                            }
                            }
                            txt_username.setText("");
                            txt_password.setText("");
                        
                            la_text.setText("");
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "You are not allowed to login");
                            txt_username.setText("");
                            txt_password.setText("");
                            
                            la_text.setText("");
                        }
                    }
                    else if(morning==false && evening==true )
                    {
                        if(rows1>0)
                        {
                            la_text.setText("Good Evening");
                            String sql = "UPDATE  `daily_attendance` set `LeavedTime`=? WHERE `Employeeid`='"+txt_username.getText().toString()+"'";

                            PreparedStatement statement = con.prepareStatement(sql);
                            statement.setString(1, la_time.getText().toString());
                    
                            int rowsupdate = statement.executeUpdate();
                            if (rowsupdate > 0)
                            {
                                JOptionPane.showMessageDialog(null,"Login Successfuly");
                            
                                try
                                {

                                    Statement statement2 = con.createStatement();
                                    ResultSet result1 = statement2.executeQuery("select * from daily_attendance");


                                    int rows=0;
                                    while(result1.next())
                                    {
                                        rows++;
                                        String idd = result1.getString(1);
                                        id="DA"+(Integer.parseInt(idd.substring(2,9))+1);
                                    }
                                    if(rows<1)
                                    {
                                        id="DA1111111";
                                    }
                                }
                                catch(SQLException ex)
                                {
                                    id="DA1111111";
                                }
                            }
                            txt_username.setText("");
                            txt_password.setText("");
                            la_text.setText("");
                        }
                        else
                        {
                            txt_username.setText("");
                            txt_password.setText("");
                            
                            la_text.setText("");
                            JOptionPane.showMessageDialog(null, "You are not allowed to login");
                        }
                    }
                    else
                    {
                        txt_username.setText("");
                        txt_password.setText("");    
                        la_text.setText("");
                        
                        JOptionPane.showMessageDialog(null, "You are not allowd to loggin");
                    }
                        
                    //JOptionPane.showMessageDialog(null,""+time);
                }
                else
                {
                    la_text.setText("");
                    txt_username.setText("");
                    txt_password.setText("");
                    JOptionPane.showMessageDialog(null, "Check your username and password");
                }
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_bt_loginActionPerformed

    private void bt_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelActionPerformed
        // TODO add your handling code here:
        txt_password.setText("");
        txt_username.setText("");
        la_text.setText("");
    }//GEN-LAST:event_bt_cancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        OverView ov= new OverView();
        ov.show();
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancel;
    private javax.swing.JButton bt_login;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel la_Date;
    private javax.swing.JLabel la_text;
    private javax.swing.JLabel la_time;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
